// <auto-generated />
namespace Piofthings.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class DeviceEndPoints : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DeviceEndPoints));
        
        string IMigrationMetadata.Id
        {
            get { return "201505040720214_DeviceEndPoints"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
